/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ededed",
        ink: "#ededed",
        body: "#888888",
        mute: "#555555",
        hairline: "#1a1a1a",
        "hairline-strong": "#333333",
        canvas: "#000000",
        "canvas-soft": "#0a0a0a",
        "canvas-soft-2": "#111111",
        link: "#3291ff",
        "link-deep": "#0070f3",
        "link-bg-soft": "#0d2137",
        success: "#3291ff",
        error: "#ee0000",
        "error-soft": "#2d1517",
        "error-deep": "#ff4444",
        warning: "#f5a623",
        "warning-soft": "#2d2410",
        "warning-deep": "#f5a623",
        violet: "#7928ca",
        "violet-soft": "#1e1433",
        "violet-deep": "#9b4dff",
        cyan: "#50e3c2",
        "cyan-soft": "#0a2e26",
        "cyan-deep": "#50e3c2",
        "highlight-pink": "#ff0080",
        "highlight-magenta": "#eb367f",
        "gradient-develop-start": "#007cf0",
        "gradient-develop-end": "#00dfd8",
        "gradient-preview-start": "#7928ca",
        "gradient-preview-end": "#ff0080",
        "gradient-ship-start": "#ff4d4d",
        "gradient-ship-end": "#f9cb28",
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Geist Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '48px', fontWeight: '600', letterSpacing: '-2.4px' }],
        'display-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-1.28px' }],
        'display-md': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.96px' }],
        'display-sm': ['20px', { lineHeight: '28px', fontWeight: '600', letterSpacing: '-0.6px' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md-strong': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '-0.28px' }],
        'body-sm-strong': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '-0.28px' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'caption-mono': ['12px', { lineHeight: '16px', fontWeight: '400', fontFamily: 'Geist Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, monospace' }],
        'code': ['13px', { lineHeight: '20px', fontWeight: '400', fontFamily: 'Geist Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, monospace' }],
        'button-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'button-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'pill-sm': '64px',
        'pill': '100px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '40px',
        '3xl': '48px',
        '4xl': '64px',
        '5xl': '96px',
        '6xl': '128px',
        'section': '192px',
      },
      boxShadow: {
        'level-1': '0 0 0 1px #ffffff0a',
        'level-2': '0px 1px 1px #ffffff06, 0px 2px 2px #ffffff08, 0 0 0 1px #ffffff0a',
        'level-3': '0px 2px 2px #ffffff06, 0px 8px 8px -8px #ffffff08, 0 0 0 1px #ffffff0a',
        'level-4': '0px 2px 2px #ffffff06, 0px 8px 16px -4px #ffffff08, 0 0 0 1px #ffffff0a',
        'level-5': '0px 1px 1px #ffffff05, 0px 8px 16px -4px #ffffff08, 0px 24px 32px -8px #ffffff0a, 0 0 0 1px #ffffff0a',
      },
    },
  },
  plugins: [],
};
